# Generated by Django 5.2.5 on 2025-08-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial_complete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating'], name='games_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['external_id'], name='games_external_id_idx'),
        ),
    ]
