# Generated by Django 5.2.5 on 2025-08-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_scalability_improvements'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_released_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='search_history_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='search_history_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='substitution',
            name='substitutions_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergame',
            name='user_games_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergame',
            name='user_games_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergame',
            name='user_games_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergame',
            name='user_games_game_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='userlibrary',
            name='user_libraries_user_id_idx',
        ),
    ]
