# Generated by Django 5.2.5 on 2025-08-21 10:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
