# Generated by Django 5.2.5 on 2025-08-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_embedding"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="substitution",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="substitution",
            name="mode",
            field=models.CharField(
                choices=[
                    ("user", "Basée sur l’utilisateur"),
                    ("game", "Basée sur le jeu"),
                ],
                default="game",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="substitution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("accepted", "Acceptée"),
                    ("rejected", "Refusée"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="substitution",
            unique_together={("user_id", "source_game", "substitute_game", "mode")},
        ),
    ]
